apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-stutech
  namespace: stutech-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-stutech
  template:
    metadata:
      labels:
        app: portal-stutech
    spec:
      containers:
      - name: portal
        image: astuani/stutech-portal:1f732ad
        ports:
        - containerPort: 80 