apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-stutech
  namespace: stutech-prod
spec:
  replicas: 2 # Para ter alta disponibilidade no seu laboratório
  selector:
    matchLabels:
      app: portal-stutech
  template:
    metadata:
      labels:
        app: portal-stutech
    spec:
      containers:
      - name: portal
        image: astuani/stutech-portal:1f732ad
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portal-stutech-service
  namespace: stutech-prod
spec:
  type: LoadBalancer # Para o MetalLB te dar um IP de acesso
  selector:
    app: portal-stutech
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80