apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-cms
  namespace: stutech-prod
spec:
  replicas: 1 # Ghost com banco interno (SQLite) deve ter apenas 1 réplica
  selector:
    matchLabels:
      app: ghost-cms
  template:
    metadata:
      labels:
        app: ghost-cms
    spec:
      containers:
      - name: ghost
        image: ghost:5-alpine
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://www.stutech.com.br
        # Forçando o Ghost a usar SQLite em vez de MySQL
        - name: database__client
          value: sqlite3
        - name: database__connection__filename
          value: /var/lib/ghost/content/data/ghost.db
        - name: database__useNullAsDefault
          value: "true"
        volumeMounts:
        - name: ghost-data
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost-content-pvc