apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: stutech-prod
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.15.208
spec:
  type: LoadBalancer
  selector:
    app: ghost-cms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368